<?php namespace Academe\SagePayMsg\PaymentMethod;

/**
 * Card object to be passed to SagePay for payment of a transaction.
 * Reasonable validation is done at creation.
 * A card in the copntext of this API is a temporary ID generated by SagePay
 * in response to card details being POSTed direct to the API.
 * The transaction does not take the full card details, as would be the case
 * for SagePay Direct.
 * The card identifier lasts for 400 seconds from creation.
 */

use Exception;
use UnexpectedValueException;

use Academe\SagePayMsg\Message\CardIdentifierResponse;
use Academe\SagePayMsg\Message\SessionKeyResponse;

class Card implements PaymentMethodInterface
{
    protected $sessionKey;
    protected $cardIdentifier;

    public function __construct(SessionKeyResponse $sessionKey, CardIdentifierResponse $cardIdentifier)
    {
        $this->cardIdentifier = $cardIdentifier;
        $this->sessionKey = $sessionKey;
    }

    /**
     * Return the body partial for message construction.
     */
    public function getBody()
    {
        return array(
            'card' => array(
                'merchantSessionKey' => $this->sessionKey->getMerchantSessionKey(),
                'cardIdentifier' => $this->cardIdentifier->getCardIdentifier(),
            ),
        );
    }
}
